import type { NextConfig } from "next";

const SLUG_REDIRECTS: Array<{ source: string; destination: string }> = [
  { source: "/database/uab",        destination: "/database/university-of-alabama-school-of-dentistry" },
  { source: "/database/atsu-az",    destination: "/database/at-still-university-arizona-school-of-dentistry" },
  { source: "/database/mwu-az",     destination: "/database/midwestern-university-college-of-dental-medicine-arizona" },
  { source: "/database/cnu",        destination: "/database/california-northstate-university-college-of-dental-medicine" },
  { source: "/database/llu",        destination: "/database/loma-linda-university-school-of-dentistry" },
  { source: "/database/ucla",       destination: "/database/ucla-school-of-dentistry" },
  { source: "/database/ucsf",       destination: "/database/ucsf-school-of-dentistry" },
  { source: "/database/uop",        destination: "/database/university-of-pacific-dugoni-school-of-dentistry" },
  { source: "/database/usc",        destination: "/database/usc-ostrow-school-of-dentistry" },
  { source: "/database/westernu",   destination: "/database/western-university-health-sciences-college-of-dental-medicine" },
  { source: "/database/cu",         destination: "/database/university-of-colorado-school-of-dental-medicine" },
  { source: "/database/uconn",      destination: "/database/university-of-connecticut-school-of-dental-medicine" },
  { source: "/database/howard",     destination: "/database/howard-university-college-of-dentistry" },
  { source: "/database/lecom",      destination: "/database/lake-erie-college-osteopathic-medicine-school-of-dental-medicine" },
  { source: "/database/nsu",        destination: "/database/nova-southeastern-university-college-of-dental-medicine" },
  { source: "/database/uf",         destination: "/database/university-of-florida-college-of-dentistry" },
  { source: "/database/dcg",        destination: "/database/dental-college-of-georgia-augusta-university" },
  { source: "/database/mwu-il",     destination: "/database/midwestern-university-college-of-dental-medicine-illinois" },
  { source: "/database/siu",        destination: "/database/southern-illinois-university-school-of-dental-medicine" },
  { source: "/database/uic",        destination: "/database/university-of-illinois-chicago-college-of-dentistry" },
  { source: "/database/iu",         destination: "/database/indiana-university-school-of-dentistry" },
  { source: "/database/ui",         destination: "/database/university-of-iowa-college-of-dentistry" },
  { source: "/database/uk",         destination: "/database/university-of-kentucky-college-of-dentistry" },
  { source: "/database/uofl",       destination: "/database/university-of-louisville-school-of-dentistry" },
  { source: "/database/lsu",        destination: "/database/louisiana-state-university-school-of-dentistry" },
  { source: "/database/une",        destination: "/database/university-of-new-england-college-of-dental-medicine" },
  { source: "/database/umd",        destination: "/database/university-of-maryland-school-of-dentistry" },
  { source: "/database/bu",         destination: "/database/boston-university-school-of-dental-medicine" },
  { source: "/database/harvard",    destination: "/database/harvard-school-of-dental-medicine" },
  { source: "/database/tufts",      destination: "/database/tufts-university-school-of-dental-medicine" },
  { source: "/database/udm",        destination: "/database/university-of-detroit-mercy-school-of-dentistry" },
  { source: "/database/umich",      destination: "/database/university-of-michigan-school-of-dentistry" },
  { source: "/database/umn",        destination: "/database/university-of-minnesota-school-of-dentistry" },
  { source: "/database/ummc",       destination: "/database/university-of-mississippi-school-of-dentistry" },
  { source: "/database/atsu-mo",    destination: "/database/at-still-university-missouri-school-of-dentistry" },
  { source: "/database/umkc",       destination: "/database/university-of-missouri-kansas-city-school-of-dentistry" },
  { source: "/database/creighton",  destination: "/database/creighton-university-school-of-dentistry" },
  { source: "/database/unmc",       destination: "/database/university-of-nebraska-medical-center-college-of-dentistry" },
  { source: "/database/unlv",       destination: "/database/university-of-nevada-las-vegas-school-of-dental-medicine" },
  { source: "/database/rutgers",    destination: "/database/rutgers-school-of-dental-medicine" },
  { source: "/database/columbia",   destination: "/database/columbia-university-college-of-dental-medicine" },
  { source: "/database/nyu",        destination: "/database/nyu-college-of-dentistry" },
  { source: "/database/stony-brook",destination: "/database/stony-brook-university-school-of-dental-medicine" },
  { source: "/database/touro",      destination: "/database/touro-college-of-dental-medicine" },
  { source: "/database/ub",         destination: "/database/university-at-buffalo-school-of-dental-medicine" },
  { source: "/database/ecu",        destination: "/database/east-carolina-university-school-of-dental-medicine" },
  { source: "/database/unc",        destination: "/database/unc-adams-school-of-dentistry" },
  { source: "/database/cwru",       destination: "/database/case-western-reserve-university-school-of-dental-medicine" },
  { source: "/database/osu",        destination: "/database/ohio-state-university-college-of-dentistry" },
  { source: "/database/ou",         destination: "/database/university-of-oklahoma-college-of-dentistry" },
  { source: "/database/ohsu",       destination: "/database/oregon-health-sciences-university-school-of-dentistry" },
  { source: "/database/pitt",       destination: "/database/university-of-pittsburgh-school-of-dental-medicine" },
  { source: "/database/temple",     destination: "/database/temple-university-kornberg-school-of-dentistry" },
  { source: "/database/upenn",      destination: "/database/university-of-pennsylvania-school-of-dental-medicine" },
  { source: "/database/upr",        destination: "/database/university-of-puerto-rico-school-of-dental-medicine" },
  { source: "/database/musc",       destination: "/database/medical-university-of-south-carolina-college-of-dental-medicine" },
  { source: "/database/meharry",    destination: "/database/meharry-medical-college-school-of-dentistry" },
  { source: "/database/uthsc",      destination: "/database/university-of-tennessee-college-of-dentistry" },
  { source: "/database/tamu",       destination: "/database/texas-am-university-college-of-dentistry" },
  { source: "/database/texas-tech", destination: "/database/texas-tech-university-woody-hunt-school-of-dentistry" },
  { source: "/database/ut-h",       destination: "/database/ut-houston-school-of-dentistry" },
  { source: "/database/ut-sa",      destination: "/database/ut-san-antonio-school-of-dentistry" },
  { source: "/database/roseman",    destination: "/database/roseman-university-college-of-dental-medicine" },
  { source: "/database/uofu",       destination: "/database/university-of-utah-school-of-dentistry" },
  { source: "/database/vcu",        destination: "/database/virginia-commonwealth-university-school-of-dentistry" },
  { source: "/database/uw",         destination: "/database/university-of-washington-school-of-dentistry" },
  { source: "/database/wvu",        destination: "/database/west-virginia-university-school-of-dentistry" },
  { source: "/database/marquette",  destination: "/database/marquette-university-school-of-dentistry" },
  // Old generic blog slugs → new SEO keyword URLs
  { source: "/blog/dental-school-secondary-application-timeline", destination: "/blog/when-do-dental-schools-send-secondaries" },
  { source: "/blog/why-this-dental-school-secondary-essay-guide", destination: "/blog/how-to-write-dental-school-secondary-essays" },
  { source: "/blog/dental-school-secondary-common-prompts-guide", destination: "/blog/how-to-write-dental-school-secondary-essays" },
  { source: "/blog/dat-prep-and-secondary-application-balance", destination: "/blog/dental-school-secondary-application-cost" },
];

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "images.unsplash.com",
      },
    ],
  },
  async redirects() {
    return SLUG_REDIRECTS.map(({ source, destination }) => ({
      source,
      destination,
      permanent: true, // 301 redirect — Google transfers link equity to new URL
    }));
  },
};

export default nextConfig;
